# Numpy

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# creating Arrays

In [4]:
sample_array = np.array([1,2,3,4])

In [5]:
sample_array

array([1, 2, 3, 4])

In [6]:
sample_array2 = np.array([1,7,9,7])

In [7]:
sample_array2

array([1, 7, 9, 7])

In [8]:
# 2D Array (a Matrix) with 2 rows and 2 columns

In [9]:
sample_array_2 = np.array([[1,2],[3,4]])

In [10]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [11]:
arr1 = np.array([[10,20],[30,45]])

In [12]:
arr1

array([[10, 20],
       [30, 45]])

In [13]:
#3D Tensor(2 Matrice, each with 2 rows and 2 columns)

In [14]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [15]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# Dimension

In [17]:
#0-D Array(Scalar) 5
#1-D Array (vector) [1,2,3,4]
#2-D Array (Matrix) (rows,cplumns)
#3-D Array (Tensor) (page,row,columns)

In [18]:
# Array properties

In [19]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [20]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# shape

In [22]:
sample_array.shape

(2, 3)

In [23]:
# dimensions

In [24]:
sample_array.ndim

2

In [25]:
# total elements

In [26]:
sample_array.size

6

In [27]:
# data type

In [28]:
sample_array.dtype

dtype('int64')

In [29]:
arr =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [30]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
arr.ndim

3

In [32]:
arr.shape

(2, 2, 3)

In [33]:
arr.size

12

In [34]:
arr.dtype

dtype('int64')

In [35]:
# special Arrays

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [41]:
np.arange(3,70,10)

array([ 3, 13, 23, 33, 43, 53, 63])

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.linspace(3,4,9)

array([3.   , 3.125, 3.25 , 3.375, 3.5  , 3.625, 3.75 , 3.875, 4.   ])

In [44]:
# Indexing & Slicing

In [45]:
sample_array = np.array([10,20,30,40])

In [46]:
sample_array

array([10, 20, 30, 40])

In [47]:
sample_array[0]

np.int64(10)

In [48]:
sample_array[2]

np.int64(30)

In [49]:
sample_array[-1]

np.int64(40)

In [50]:
# Slicing

In [51]:
sample_array[1:3]

array([20, 30])

In [52]:
# Array Operations

In [53]:
a = np.array([1,2,3])

In [55]:
b = np.array ([4,5,6])

In [56]:
a

array([1, 2, 3])

In [57]:
b

array([4, 5, 6])

In [58]:
a + b

array([5, 7, 9])

In [59]:
a - b

array([-3, -3, -3])

In [60]:
a * b

array([ 4, 10, 18])

In [61]:
a / b

array([0.25, 0.4 , 0.5 ])

In [62]:
a = np.array([10,20,30])

In [63]:
b = np.array([40,50,60])

In [64]:
a

array([10, 20, 30])

In [65]:
b

array([40, 50, 60])

In [66]:
a + b

array([50, 70, 90])

In [67]:
a - b

array([-30, -30, -30])

In [68]:
a * b

array([ 400, 1000, 1800])

In [69]:
a / b

array([0.25, 0.4 , 0.5 ])

In [70]:
# Mathematical Function

In [72]:
sample_array = np.array([1,4,9])

In [73]:
sample_array

array([1, 4, 9])

In [74]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [76]:
arr = np.array([34,56,90])

In [77]:
arr

array([34, 56, 90])

In [78]:
np.sqrt(arr)

array([5.83095189, 7.48331477, 9.48683298])

In [79]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [80]:
np.exp(arr)

array([5.83461743e+14, 2.09165950e+24, 1.22040329e+39])

In [81]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [82]:
np.log(arr)

array([3.52636052, 4.02535169, 4.49980967])

In [83]:
arr1 = np.array([100,213,454])

In [84]:
np.log(arr1)

array([4.60517019, 5.36129217, 6.1180972 ])

In [85]:
# Statistical Functions

In [86]:
sample_array = np.array([1,2,3,4,5])

In [87]:
sample_array

array([1, 2, 3, 4, 5])

In [88]:
np.mean(sample_array)

np.float64(3.0)

In [89]:
np.median(sample_array)

np.float64(3.0)

In [90]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [91]:
np.min(sample_array)

np.int64(1)

In [92]:
np.max(sample_array)

np.int64(5)

In [93]:
# Reshaping Arrays

In [94]:
arr = np.arange(0,6)

In [95]:
arr

array([0, 1, 2, 3, 4, 5])

In [96]:
reshaped = arr.reshape(2,3)

In [97]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [98]:
# Flattening 

In [99]:
arr = np.array([[1,2],[3,4]])

In [100]:
arr

array([[1, 2],
       [3, 4]])

In [101]:
arr.flatten()

array([1, 2, 3, 4])

In [102]:
arr =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [103]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [104]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
# Joining Arrays

In [106]:
arr1 = np.array([1,2,3,4,5])

In [107]:
arr2 = np.array([6,7,8,9,10])

In [108]:
arr1

array([1, 2, 3, 4, 5])

In [109]:
arr2

array([ 6,  7,  8,  9, 10])

In [110]:
np.concatenate((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
# Splitting Arrays

In [112]:
arr = np.array([1,2,3,4,5])

In [113]:
arr

array([1, 2, 3, 4, 5])

In [114]:
np.array_split(arr,2)

[array([1, 2, 3]), array([4, 5])]

In [115]:
np.split(arr,5) # only for equal split

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [116]:
# Random Module

In [117]:
np.random.rand(3)

array([0.63559417, 0.95269392, 0.10376659])

In [118]:
np.random.randint(1,10,5)

array([5, 4, 6, 4, 9], dtype=int32)

In [119]:
# Axis Concept

In [120]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [121]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [122]:
# for addition
# coloum = 0
# row = 1

In [123]:
np.sum(arr,axis=0)

array([ 7,  9, 11, 13, 15])

In [124]:
np.sum(arr,axis = 1)

array([15, 40])

In [125]:
# NaN (not a number) & Missing values

In [126]:
sample_array = np.array([1,np.nan,3])

In [127]:
sample_array

array([ 1., nan,  3.])

In [128]:
np.isnan(sample_array)

array([False,  True, False])

In [129]:
# practice
#create two numpy arrays and perform element wise addition substraction muultiplication and modulus operations

In [130]:
arr1 = np.array([10,20,30,40])

In [131]:
arr2 = np.array([2,4,5,6])

In [132]:
arr1 + arr2

array([12, 24, 35, 46])

In [133]:
arr1 - arr2

array([ 8, 16, 25, 34])

In [134]:
arr1 * arr2

array([ 20,  80, 150, 240])

In [135]:
arr1 % arr2

array([0, 0, 0, 4])